steps:
  # Build and push DB image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloudcomputing-451405/db-pod:latest', './SingleNodeforDevelopmentEnvironment/db-pod']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloudcomputing-451405/db-pod:latest']

  # Build and push Web image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloudcomputing-451405/web-pod:latest', './SingleNodeforDevelopmentEnvironment/web-pod']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloudcomputing-451405/web-pod:latest']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'apply'
      - '-f'
      - 'SingleNodeforDevelopmentEnvironment/db-deployment.yaml'
      - '-f'
      - 'SingleNodeforDevelopmentEnvironment/db-service.yaml'
      - '-f'
      - 'SingleNodeforDevelopmentEnvironment/nginx-deployment.yaml'
      - '-f'
      - 'SingleNodeforDevelopmentEnvironment/nginx-service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

images:
  - 'gcr.io/cloudcomputing-451405/db-pod:latest'
  - 'gcr.io/cloudcomputing-451405/web-pod:latest'
